github_url = "custom-stack-size-data-pack"

[version]
current = "1.0.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"
[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "beet.json"

[[file]]
src = "beet-release.json"

[[file]]
src = "datapack/data/ab.custom-stack-size/functions/load.mcfunction"

[[file]]
src = "datapack/data/ab.custom-stack-size/functions/install.mcfunction"

[[file]]
src = "datapack/data/americanbagel/advancements/ab.custom-stack-size/root.json"